name: DevSecOps Pipline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  component-analysis-npm-audit:
    name: Component Analysis and NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14'
      - name: create log file
        run: npm i --package-lock-only
      - name: lock
        run: npm config set package-lock true
      - name: install npm
        run: npm install -g npm@latest
      - name: update npm
        run: npm i -g npm-upgrade
      - name: Run NPM Audit
        run: npm audit --json > npm-audit.json
      - name: Upload NPM Audit Report
        uses: actions/upload-artifact@v3
        with:
          name: npm-audit-report
          path: npm-audit.json

  build-dummy:
    name: Build Echo Statement
    runs-on: ubuntu-latest
    steps:
      - name: Echo Building Going On
        run: echo "Echo Building Going on!!"

  deploy-dummy:
    name: Deploy Echo Statement
    runs-on: ubuntu-latest
    needs: build-dummy
    steps:
      - name: Echo Deploying Going On
        run: echo "Echo Deploying Going on!!"